-- =====================================================================
-- Event/Club Platform (Multi-University) — PostgreSQL DDL
-- Date: 2025-11-25
-- =====================================================================

BEGIN;

-- Extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS btree_gist;
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS citext;

SET TIME ZONE 'UTC';

-- Lookups
CREATE TABLE IF NOT EXISTS roles (
  id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key TEXT UNIQUE NOT NULL,
  label TEXT NOT NULL
);
INSERT INTO roles(key,label) VALUES
 ('org_admin','Organization Admin'),
 ('club_admin','Club Admin'),
 ('venue_admin','Venue Admin'),
 ('staff','Staff / Editor'),
 ('student','Student'),
 ('guest','Guest')
ON CONFLICT (key) DO NOTHING;

CREATE TABLE IF NOT EXISTS visibility_types (
  id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key TEXT UNIQUE NOT NULL,
  label TEXT NOT NULL
);
INSERT INTO visibility_types(key,label) VALUES
 ('public','Public'),
 ('unlisted','Unlisted (direct link)'),
 ('private','Private (members only)')
ON CONFLICT (key) DO NOTHING;

CREATE TABLE IF NOT EXISTS signup_statuses (
  id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key TEXT UNIQUE NOT NULL,
  label TEXT NOT NULL
);
INSERT INTO signup_statuses(key,label) VALUES
 ('active','Active'),
 ('cancelled','Cancelled'),
 ('waitlist','Waitlist'),
 ('checked_in','Checked-in')
ON CONFLICT (key) DO NOTHING;

CREATE TABLE IF NOT EXISTS event_statuses (
  id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key TEXT UNIQUE NOT NULL,
  label TEXT NOT NULL
);
INSERT INTO event_statuses(key,label) VALUES
 ('draft','Draft'),
 ('published','Published'),
 ('cancelled','Cancelled'),
 ('archived','Archived')
ON CONFLICT (key) DO NOTHING;

CREATE TABLE IF NOT EXISTS venue_types (
  id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key TEXT UNIQUE NOT NULL,
  label TEXT NOT NULL
);
INSERT INTO venue_types(key,label) VALUES
 ('hall','Hall'),
 ('classroom','Classroom'),
 ('lab','Laboratory'),
 ('outdoor','Outdoor'),
 ('auditorium','Auditorium'),
 ('theatre','Theatre'),
 ('sports','Sports Area')
ON CONFLICT (key) DO NOTHING;

-- Universities & campuses
CREATE TABLE IF NOT EXISTS universities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  locale TEXT NOT NULL DEFAULT 'tr-TR',
  timezone TEXT NOT NULL DEFAULT 'Europe/Istanbul',
  website TEXT,
  color_primary TEXT,
  color_secondary TEXT,
  logo_url TEXT,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at timestamptz
);

CREATE TABLE IF NOT EXISTS campuses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  university_id BIGINT NOT NULL REFERENCES universities(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  address TEXT,
  geo_point POINT,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at timestamptz,
  UNIQUE (university_id, name)
);

-- Users & RBAC
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  university_id BIGINT NOT NULL REFERENCES universities(id) ON DELETE CASCADE,
  email CITEXT NOT NULL,
  name TEXT NOT NULL,
  phone TEXT,
  student_no TEXT,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at timestamptz,
  UNIQUE (university_id, email)
);
CREATE INDEX IF NOT EXISTS idx_users_uni ON users(university_id);
CREATE INDEX IF NOT EXISTS idx_users_email_trgm ON users USING gin (email gin_trgm_ops);

CREATE TABLE IF NOT EXISTS user_roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  university_id BIGINT NOT NULL REFERENCES universities(id) ON DELETE CASCADE,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  role_id SMALLINT NOT NULL REFERENCES roles(id) ON DELETE RESTRICT,
  club_id BIGINT,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (university_id, user_id, role_id, club_id)
);

-- Clubs
CREATE TABLE IF NOT EXISTS clubs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  university_id BIGINT NOT NULL REFERENCES universities(id) ON DELETE CASCADE,
  campus_id BIGINT REFERENCES campuses(id) ON DELETE SET NULL,
  name TEXT NOT NULL,
  slug TEXT NOT NULL,
  description TEXT,
  cover_url TEXT,
  social_links JSONB,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at timestamptz,
  UNIQUE (university_id, slug)
);
CREATE INDEX IF NOT EXISTS idx_clubs_uni ON clubs(university_id);
CREATE INDEX IF NOT EXISTS idx_clubs_name_trgm ON clubs USING gin (name gin_trgm_ops);

CREATE TABLE IF NOT EXISTS club_memberships (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  university_id BIGINT NOT NULL REFERENCES universities(id) ON DELETE CASCADE,
  club_id BIGINT NOT NULL REFERENCES clubs(id) ON DELETE CASCADE,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title TEXT,
  joined_at timestamptz DEFAULT CURRENT_TIMESTAMP,
  left_at timestamptz,
  UNIQUE (club_id, user_id)
);
CREATE INDEX IF NOT EXISTS idx_club_memberships_uni ON club_memberships(university_id);
CREATE INDEX IF NOT EXISTS idx_club_memberships_club ON club_memberships(club_id);

-- Venues & blocks
CREATE TABLE IF NOT EXISTS venues (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  university_id BIGINT NOT NULL REFERENCES universities(id) ON DELETE CASCADE,
  campus_id BIGINT REFERENCES campuses(id) ON DELETE SET NULL,
  name TEXT NOT NULL,
  code TEXT,
  capacity INTEGER CHECK (capacity IS NULL OR capacity >= 0),
  location TEXT,
  geo_point POINT,
  features JSONB,
  type_id SMALLINT REFERENCES venue_types(id) ON DELETE RESTRICT,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at timestamptz,
  UNIQUE (university_id, name, campus_id)
);
CREATE INDEX IF NOT EXISTS idx_venues_uni ON venues(university_id);

CREATE TABLE IF NOT EXISTS venue_blocks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venue_id BIGINT NOT NULL REFERENCES venues(id) ON DELETE CASCADE,
  start_at timestamptz NOT NULL,
  end_at timestamptz NOT NULL,
  reason TEXT,
  created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (start_at < end_at)
);
CREATE INDEX IF NOT EXISTS idx_venue_blocks_range ON venue_blocks USING gist (tstzrange(start_at, end_at));
ALTER TABLE venue_blocks
  ADD CONSTRAINT venue_blocks_no_overlap EXCLUDE USING gist (
    venue_id WITH =,
    tstzrange(start_at, end_at) WITH &&
  );

-- Tags
CREATE TABLE IF NOT EXISTS tags (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_tags_trgm ON tags USING gin (name gin_trgm_ops);

-- Events
CREATE TABLE IF NOT EXISTS events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  university_id BIGINT NOT NULL REFERENCES universities(id) ON DELETE CASCADE,
  club_id BIGINT NOT NULL REFERENCES clubs(id) ON DELETE CASCADE,
  venue_id BIGINT REFERENCES venues(id) ON DELETE SET NULL,
  visibility_id SMALLINT NOT NULL REFERENCES visibility_types(id) ON DELETE RESTRICT,
  status_id SMALLINT NOT NULL REFERENCES event_statuses(id) ON DELETE RESTRICT,
  title TEXT NOT NULL,
  slug TEXT NOT NULL,
  description TEXT,
  start_at timestamptz NOT NULL,
  end_at timestamptz NOT NULL,
  capacity INTEGER CHECK (capacity IS NULL OR capacity >= 0),
  is_free BOOLEAN NOT NULL DEFAULT TRUE,
  price_minor INTEGER CHECK (price_minor IS NULL OR price_minor >= 0),
  currency CHAR(3) DEFAULT 'TRY',
  banner_url TEXT,
  links JSONB,
  created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at timestamptz,
  CHECK (start_at < end_at),
  UNIQUE (university_id, slug)
);
CREATE INDEX IF NOT EXISTS idx_events_uni ON events(university_id);
CREATE INDEX IF NOT EXISTS idx_events_time ON events(start_at, end_at);
CREATE INDEX IF NOT EXISTS idx_events_title_trgm ON events USING gin (title gin_trgm_ops);

ALTER TABLE events
  ADD CONSTRAINT events_no_room_overlap EXCLUDE USING gist (
    venue_id WITH =,
    tstzrange(start_at, end_at) WITH &&
  )
  WHERE (venue_id IS NOT NULL AND status_id = (SELECT id FROM event_statuses WHERE key='published'));

CREATE TABLE IF NOT EXISTS event_tags (
  event_id BIGINT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
  tag_id BIGINT NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
  PRIMARY KEY (event_id, tag_id)
);

-- Signups
CREATE TABLE IF NOT EXISTS event_signups (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id BIGINT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  email CITEXT NOT NULL,
  student_no TEXT,
  phone TEXT,
  token_uuid UUID NOT NULL DEFAULT uuid_generate_v4(),
  status_id SMALLINT NOT NULL REFERENCES signup_statuses(id) ON DELETE RESTRICT
    DEFAULT (SELECT id FROM signup_statuses WHERE key='active'),
  notes TEXT,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (event_id, email)
);
CREATE INDEX IF NOT EXISTS idx_event_signups_event ON event_signups(event_id);
CREATE INDEX IF NOT EXISTS idx_event_signups_email_trgm ON event_signups USING gin (email gin_trgm_ops);

CREATE TABLE IF NOT EXISTS waitlist_promotions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id BIGINT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
  signup_id BIGINT NOT NULL REFERENCES event_signups(id) ON DELETE CASCADE,
  promoted_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (event_id, signup_id)
);

-- Checkins & Media
CREATE TABLE IF NOT EXISTS checkins (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id BIGINT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
  signup_id BIGINT REFERENCES event_signups(id) ON DELETE SET NULL,
  scanned_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  method TEXT,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_checkins_event ON checkins(event_id);

CREATE TABLE IF NOT EXISTS media (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  university_id BIGINT NOT NULL REFERENCES universities(id) ON DELETE CASCADE,
  owner_type TEXT NOT NULL,
  owner_id BIGINT NOT NULL,
  kind TEXT NOT NULL,
  url TEXT NOT NULL,
  meta JSONB,
  created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_media_owner ON media(owner_type, owner_id);
CREATE INDEX IF NOT EXISTS idx_media_uni ON media(university_id);

-- Email logs & audit
CREATE TABLE IF NOT EXISTS email_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  university_id BIGINT NOT NULL REFERENCES universities(id) ON DELETE CASCADE,
  category TEXT NOT NULL,
  recipient CITEXT NOT NULL,
  subject TEXT NOT NULL,
  payload JSONB,
  sent_at timestamptz,
  error TEXT,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_email_logs_uni ON email_logs(university_id);
CREATE INDEX IF NOT EXISTS idx_email_logs_recipient_trgm ON email_logs USING gin (recipient gin_trgm_ops);

CREATE TABLE IF NOT EXISTS audit_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  university_id BIGINT REFERENCES universities(id) ON DELETE SET NULL,
  actor_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  event_type TEXT NOT NULL,
  entity_type TEXT NOT NULL,
  entity_id BIGINT,
  payload JSONB,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_audit_events_uni ON audit_events(university_id);
CREATE INDEX IF NOT EXISTS idx_audit_events_type ON audit_events(event_type);

-- MV for public events
CREATE MATERIALIZED VIEW IF NOT EXISTS mv_public_events AS
SELECT
  e.id,
  e.university_id,
  e.title,
  e.description,
  e.start_at,
  e.end_at,
  e.banner_url,
  c.name AS club_name,
  v.name AS venue_name
FROM events e
JOIN clubs c ON c.id = e.club_id
LEFT JOIN venues v ON v.id = e.venue_id
WHERE e.deleted_at IS NULL
  AND e.status_id = (SELECT id FROM event_statuses WHERE key='published');

CREATE INDEX IF NOT EXISTS idx_mv_public_events_time ON mv_public_events(start_at);
CREATE INDEX IF NOT EXISTS idx_mv_public_events_title_trgm ON mv_public_events USING gin (title gin_trgm_ops);

-- Seed a sample university
INSERT INTO universities(slug, name)
VALUES ('aybu','Ankara Yildirim Beyazit University')
ON CONFLICT (slug) DO NOTHING;

COMMIT;
