"""final naming convention fix

Revision ID: 45da6e25ad28
Revises: 
Create Date: 2025-12-01 00:37:39.213108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45da6e25ad28'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_community_name'), ['name'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('major', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_user_username'), ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_username'), type_='unique')
        batch_op.drop_column('major')
        batch_op.drop_column('username')

    with op.batch_alter_table('community', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_community_name'), type_='unique')

    # ### end Alembic commands ###
